# Generated by Django 6.0.5 on 2026-05-18 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('log_date', models.DateField()),
                ('miles_driven_today', models.FloatField(default=0)),
                ('carrier_name', models.CharField(max_length=100)),
                ('office_address', models.CharField(max_length=200)),
                ('truck_number', models.CharField(max_length=100)),
                ('shipping_doc', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-log_date'],
            },
        ),
        migrations.CreateModel(
            name='DutyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_type', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty_nd', 'On Duty - Not Driving')], max_length=20)),
                ('start_hour', models.FloatField()),
                ('end_hour', models.FloatField()),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('driver_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_entries', to='logs.driverlog')),
            ],
        ),
    ]
